<div id="zm_main">
<div class="zm_page-title">
     <h2 class="color_blue" style="text-align:center; font-family: georgia;font-size: 24px;"><b>HOSTED MAILBOX BILLING</b></h2>
    <h3 class="color_blue"><p style="text-align:center;">Sharing Files, Documents, Calendars, Contacts with Colleagues Inside and </p><p style="text-align:center;"> Outside your Organization Made Easier than Ever Before!</p></h3>
</div>
  <div class="zm_intro">			
    <p style="font-weight:bold;color:#3D6611;">Sorry your payment process is not successful. Please try again !!</p>
    <p><a href="<?php echo 'http://'.$_SERVER['SERVER_NAME'].'/zmb'; ?>" class="zmb_login_reg">Click here</a> to purchase a plan.</p>			
  </div>

 <div class="clear"></div>
</div>
<style>
.breadcrumbs{
	display:none !important;	
}
</style>